version: '3.9'

services:
  webapp:
    image: node:19.7-alpine3.17
    container_name: nest_playground
    working_dir: "/backend"
    volumes:
      - ./:/backend
    command: "sh -c 'yarn install && yarn run start:dev'"
    # command: "sh -c 'sleep infinity'"
    ports:
      - "3000:3000"
    environment:
      HOST: 0.0.0.0
